name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Python Semantic Release
      run: pip install python-semantic-release==7.15.4
    
    - name: Release 
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "action@github.com"
        semantic-release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}